### ISSUE TITLE
Write Content for the Need Help page

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#116]
Work with @MerlinEgalite on this!

**Comment by tamarandom** [comment]
Hey @krisjpi !! Just FYI that this was removed in the staging env for now.  If you and @MerlinEgalite have a working draft doc for this, would you drop it here please?  TBD if this is added back after go-live. @GriffGreen please correct if that is wrong.

![Screen Shot 2021-02-02 at 3.18.33 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/1833ce25-7820-4e98-a60e-8c720b1baa1c)

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2021-02-11 at 16 02 02" src="https://user-images.githubusercontent.com/44097430/107654059-92d65380-6c82-11eb-9169-a7e5121ab1bd.png">

This is pretty ugly but it could be not far from that with some basic questions a wannabe member could ask :)

**Comment by GriffGreen** [comment]
oooooo! @MerlinEgalite that looks AWESOME! I didn't know you were a designer too!

**Comment by MerlinEgalite** [comment]
@krisjpi do you have the content ? just to update this issue 😄

**Comment by MerlinEgalite** [comment]
<img width="1440" alt="Screenshot 2021-03-31 at 21 35 03" src="https://user-images.githubusercontent.com/44097430/113207790-58943600-9271-11eb-88a2-acb2ad248cff.png">

content added

**Comment by GriffGreen** [comment]
@MerlinEgalite AMAZING!!! SO fast! 

Can I add 1 more: 

**What liabilities are removed by the legal protection of the Swiss Association?** 

The Trusted Seed doesn't remove any liabilities. Unfortunately, if you hold tokens in a DAO or Commons, in many jurisdictions you can be held 100% individually liable for any actions made by the DAO. However, if you are a Member of our Trusted Seed, and you were acting in good faith as a member of a qualified DAO, we will fight for you! We will pay your legal fees and rally support from the greater community.

**Comment by MerlinEgalite** [comment]
Sure we'll do!
