### ISSUE TITLE
Even tho I have reached my max trust score, i should still be able to donate

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#191]
But the app won't let me :-(
![Screen Shot 2021-02-28 at 10.29.26 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/686a13a7-0f3d-46ce-8d62-0d4f0df465f4)

**Comment by MerlinEgalite** [comment]
What is the complete process?
You already have CSTK tokens but you're not a member right? Is there an error message on the right?

**Comment by mendesfabio** [comment]
Actually, besides that problem reported by @GriffGreen, maybe we relabel all buttons after users pay dues. If they've already paid dues, the text in the button could be `Contribute`.

**Comment by tamarandom** [comment]
Hey @mendesfabio There is a 1.4% tax on donations and contributions. These are dues. Should not use the words contribute or donation. More dues can be paid. ;)


Hey @MerlinEgalite The use case is that the individual has reached their max score and will not receive any more CSTK token for their membership dues BUT they should still be allowed to pay more dues. Let me know if that's not clear.

**Comment by MerlinEgalite** [comment]
Okay so If I understand I should keep "Pay Membership Due" even after the person has already paid its dues once?

**Comment by mendesfabio** [comment]
I think so, @MerlinEgalite. 

Thanks for the explanation @tamarandom, really didn't know about it.

**Comment by tamarandom** [comment]
Always “Membership Dues”, yes.
