### ISSUE TITLE
Button with unclear context: Add CSTK to MetaMask 

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#193]
The action of the below "Add CSTK…" button is a bit unclear. At least, it confused me. As "if I already have a membership score, I have tokens, why would I want/need also to add them to MetaMask?"
 
<img width="439" alt="Skärmavbild 2021-03-02 kl  12 08 09" src="https://user-images.githubusercontent.com/9698363/109726604-4b712200-7bb3-11eb-9f91-a536038234f1.png">

## Suggestion

To clarify what kind of adding we are talking about here, perhaps instead of a button there could be a short explanatory text/tip?

Something like: 

**💡 TIP:** Your CSTK score doesn't automatically become visible in MetaMask, click here to [add your tokens](#). 

or 

**💡 TIP:** Don't see your CSTK score in MetaMask? [Click here to configure MetaMask to find them](#).

**Comment by tamarandom** [comment]
Hey @kristoferlund ! Thanks for this. 
@mendesfabio @MerlinEgalite Is adding a tooltip next to the Score something we can do?

**Comment by MerlinEgalite** [comment]
Sure we can do it!
But I'm not sure about the best way to show this to the user.. on hover on the score we show the tooltip?

**Comment by kristoferlund** [comment]
Could something like this work? Then you wouldn't have to do a tooltip.

![Skärmavbild 2021-03-03 kl  15 24 42](https://user-images.githubusercontent.com/9698363/109819959-d9412180-7c34-11eb-8ec5-3d49de049467.png)

**Comment by mendesfabio** [comment]
Yeah, I don't think we need a tooltip. Changing the text, as @kristoferlund suggests, seems to solve this problem.

**Comment by tamarandom** [comment]
Update : The other challenge is that the individual needs to also change to xDAI network in Metamask. 
This may be more complicated than it will be worth keeping this nice-to-have "add to Metamask" functionality. 

Action to take: remove the Add to Metamask. 

(Alternative option, @mendesfabio, if you love this to the moon, then we can move it to the Thank you Page. DM @GriffGreen if need more details).

**Comment by tamarandom** [comment]
I'm reopening this because we did not remove the "Add to Metamask

I am checking here https://develop--tech-dapp.netlify.app/pay-dues and here https://member.commonsstack.foundation/pay-dues <-- is there another place I should be looking?

**Comment by tamarandom** [comment]
Update : Remove it from all places in the user journey. There is a second message to ask "Add to Metamask" post payment of dues. Get rid of it there too.
