### ISSUE TITLE
Wording "contribution"

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#206]
@krisjpi Would you please confirm that leaving the word "contribution" in the Terms is ok with legal. ![photo_2021-03-11_14-31-19.jpg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/b23b145a-4ff9-47a6-be6d-4a3295ab1b25)

**Comment by krisjpi** [comment]
I think the way it is worded is close enough to be lumped in with Membership Dues, but something we should look at amending at the next board meeting for consistency. Thank you for flagging me here!

**Comment by krisjpi** [comment]
After speaking with Coach B about this, using contribution here should be fine as is - no changes required!
