### ISSUE TITLE
Tooltips explaining CSTK score and Membership score

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#210]
Popup tooltips next to the headers of CSTK Score and Membership Score could help the user better understand the differences between the two terms. 

Citing @tamarandom from Discord:
> Allow me to explain. All current Trusted Seed have a current CSTK score. The membership score is zero until membership dues have been paid. Once membership dues have been paid, the membership score becomes the individual's Trusted Seed score plus the additional CSTK score gained by paying membership dues. So there is a distinction between these two figures before the membership dues have been paid. 

Possibly it would be a good idea to do tooltips for "Terms and conditions" and "Statutes" as well.

**Comment by MerlinEgalite** [comment]
@kristoferlund what do you propose for the "Terms and conditions" and "Statutes" tooltips?

**Comment by kristoferlund** [comment]
Suggestions:

The Terms & Conditions apply to your membership of the Commons Stack Association. It covers planned activities, membership, rights & duties, membership score, risks, etc.

The Statutes describe and regulate the structure and governance of the Commons Stack Association.

I'd like to check texts with @GriffGreen, @tamarandom or someone else knowledgable and good with words as well.

**Comment by GriffGreen** [comment]
The Terms & Conditions apply to your membership of the Trusted Seed's Swiss Association. It covers planned activities, membership, rights & duties, membership score, risks, etc.

The Statutes describe and regulate the structure and governance of the Trusted Seed's Swiss Association.
