### ISSUE TITLE
Fix the Pending CSTK Tokens vs CSTK Score 

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#211]
![Screen Shot 2021-03-12 at 8.31.54 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/87e2165c-bbf1-4f60-9841-9241253942b3)

In the bottom left it should be titled: "Your Pending Membership Score" and when when the person has a Score up at the top, we turn that number to 0, and remove the "You haven't paid dues yet" text.

**Comment by kristoferlund** [comment]
Great, that makes the relationship between the two terms more clear.

**Comment by tamarandom** [comment]
Hiya @mendesfabio ! Can you take this on ?
