### ISSUE TITLE
Design : A welcome screen before the legal text pops up

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#218]
(Sync with @kristoferlund on this one)

**Comment by kristoferlund** [comment]
Yep, a screen that gives the user a bit of context and understanding of which are the different steps in the process of becoming a member.

Some kind of timeline design?

![image](https://user-images.githubusercontent.com/9698363/111532131-a6834700-8765-11eb-8393-51a5ced47dc9.png)

**Comment by tamarandom** [comment]
🙌🏼  Nice!

**Comment by markoprljic** [comment]
Where can I find the content for this popup? Roughly I know what the steps are:

1. Apply to become a member of the Trusted Seed (fill in form, submit etc.)
2. Make sure you have 450 DAI and CSTK tokens in your wallet 
3. Sign the Terms and conditions
4. Continue with the application process

I don't know, please someone to provide the final content and I can mock up a popup screen.
Thanks.

**Comment by tamarandom** [comment]
Update : 

Welcome to the Trusted Seed's Swiss Membership DApp! 
 
If you have already been accepted into the Trusted Seed, activate your membership now.

Your next steps are to: 
1. Sign in with you wallet 
1. Sign the Statutes and the Terms & Conditions
2. Pay your membership dues (for which you will need DAI and a little ETH in your wallet)

Ready to get started? 

[  Let's go button ] 

---
**Functionality** : the [Let's go button] will sign into their wallet

**Comment by markoprljic** [comment]
👍

**Comment by markoprljic** [comment]
Here it is. Let me know if anything else needed.

![Image 2021-03-26 at 12 07 26 pm](https://user-images.githubusercontent.com/5704285/112622834-e0221500-8e2b-11eb-8d1e-675e8b1a7bf3.jpg)

[Figma source here.](https://www.figma.com/file/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?node-id=2031%3A6835)

**Comment by kristoferlund** [comment]
Looks good! Will implement, push to develop branch and wait for additional comments before move to production.

**Comment by kristoferlund** [comment]
Before I go ahead and do the Welcome screen, can we just verify the flow for the first few screens? Here's a diagram:

https://miro.com/app/board/o9J_lNU14ec=/

**Comment by markoprljic** [comment]
@kristoferlund Reviewed and left few comments.

**Comment by kristoferlund** [comment]
Update: Will be done tomorrow hopefully.

**Comment by kristoferlund** [comment]
Done, see preview before merge at: https://deploy-preview-229--tech-dapp-develop.netlify.app/
