### ISSUE TITLE
Error Message destabilizes Contribute Form feng shui

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#222]
https://user-images.githubusercontent.com/9698363/111624109-9150fb80-87eb-11eb-8649-9606cbcddb68.mov

**Comment by tamarandom** [comment]
Nice catch!

**Comment by MerlinEgalite** [comment]
We can replace that by a red bow and a warning tooltip maybe?

**Comment by tamarandom** [comment]
Update : to be explored. ;)
