### ISSUE TITLE
What to do about mobile?

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#231]
The app doesn't look and work good on mobile. Totally fixable but is it worth it?

Another alternative would be to put up a screen for mobile users saying that the app is desktop only for now. In the spirit of not overengineering. And then for a future version (year 2) we make it a glimmering jewel of mobile first design.

![image](https://user-images.githubusercontent.com/9698363/112979045-5d18fb80-9158-11eb-9b86-3499493a54ec.png)

**Comment by tamarandom** [comment]
Can't resize to read the pop-up.
Can't sign the T&C and Statutes.

Mobile is out of scope.

We need to redirect visitors to the desktop version.
