### ISSUE TITLE
Remove "whitelist" and "white list" everywhere in the DApp replacing it with Registry

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#240]
![Screen Shot 2021-04-05 at 12.47.02 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/d3f76f31-d50b-47f2-9155-4852332b9c41)

"Trusted Seed Registry"

**Comment by kristoferlund** [comment]
Good change! Whitelist is a bit misleading. 

"The connected address is not in the Trusted Seed registry" 

And for the button:

"Apply for membership"
