### ISSUE TITLE
Member wants to pay additional dues should not see this message 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#247]
When someone is already a member and wants to pay more dues, this message should not pop up. There should be no minimum to how much additional dues someone may pay.

![Screen Shot 2021-04-26 at 1.26.23 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/be1f454a-7946-48cc-86ed-23f2151c0dcc)

**Comment by GriffGreen** [comment]
Yep there should be no minimum
