### ISSUE TITLE
Problem paying membership dues

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#248]
The person using this address is not able to complete paying his membership dues : 0x02317BB3f16cE21e9239C217B21Bd18Aa24ab0D3
https://etherscan.io/address/0x02317BB3f16cE21e9239C217B21Bd18Aa24ab0D3

He says the screen he sees is this and then it takes him back to the initial page. 
![Screen Shot 2021-04-26 at 1.31.17 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/4007f4d7-5e20-44d0-a405-bc6a13d21d52)

**Comment by aminlatifi** [comment]
The transaction wasn't created by Metamask, probably the wallet has some issue.
