### ISSUE TITLE
Final step: Shut down old contracts

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#269]
Everything ok!? Remove admins from old contracts, in effect killing them.

**Comment by kristoferlund** [comment]
If not done yet, remove permissions the permissions to call `dao.mint()`from the old Minter contract: 0x9f92813542Fc66Cd0e530501b4ec62B982B0dEb9

**Comment by GriffGreen** [comment]
Votes passed... removed 2 minters, that one and a test one

<img width="716" alt="Screen Shot 2021-06-04 at 1 18 37 PM" src="https://user-images.githubusercontent.com/14945613/120852427-797f4d00-c57a-11eb-984b-0a8be178ff10.png">
