### ISSUE TITLE
Trusted Seed Members List

### ISSUE THREAD

**Issue by knobsdao** [commons-stack/swissmem-dapp#272]
This issue follows [issue 9 from CS Workspace](https://github.com/commons-stack/iteration0/issues/9), to create a list of top members of TS and showcase it to our community. At the moment, there's a general list for internal use.

**Comment by kristoferlund** [comment]
## The transparency list
- Build it like a static page for now 
- A tab in swiss membership dapp
- Ask Marko for design
- Dan keeps an external spreadsheet with names and adresses
- Segments the list into three groups
- Rank on max trust score or on CSTK amount

**Comment by markoprljic** [comment]
- Define what are the 3 groups (categories) to be filters / tabs
- Include list sorting ascending/descending
- quick search by name
- Title and subtitle (description) to be defined

If we want to have Stats/Chart section below header and above the list:

- Total number of CSTK all members
- Total number of CSTK by segment/category
- Other?

**Comment by kristoferlund** [comment]
We haven't discussed sorting, searching and/or filtering. Is there a need? Currently the trusted seed has ca 175 members (I think). Divided in three groups. Perhaps the list will be short enough not to need search/filter?

If we feel there is a need, of course, let's build it!

Ping @knobsdao @tamarandom @GriffGreen

**Comment by markoprljic** [comment]
I agree, what is not needed we don't have to invest time and effort there. I propose to come to final spec on possible stats and filters so that we can continue with the work.

**Comment by GriffGreen** [comment]
Sorting should just be alphabetical or something benign like that 

I believe the idea was to have it grouped by maxTrustScore (but not sorted by such)

Maybe the top 25 max trust scores, then the next 50, then the rest? thats a starting idea, but i am in no way attached to any ideas. The main requirements are:

Good names should be at the top! Zargham, Simon, Trent, Luke, etc

We want to avoid connecting addresses to names... so we can't sort by anything on chain... groupings in big bunches is ok

**Comment by kristoferlund** [comment]
Ok, based on what you all said here and discussion in Discord, how about this spec?

![image](https://user-images.githubusercontent.com/9698363/121241170-6da5ca80-c89b-11eb-8513-1486dba5ca2d.png)

Music festival style to differentiate segments in a simple way? Kanye gets big font, Meatloaf gets small font. Zargham gets big font, kristofer gets small font.

Editable Miro: https://miro.com/app/board/o9J_lAVV1Fg=/

**Comment by markoprljic** [comment]
@kristoferlund Thanks for the mockup, the header and stats look good. I'm not in favor of visually differentiating members with bigger/smaller fonts. I'd rather see a standard list below and segments just be filter either at the top of the table or on the stats chart. 

![Image 2021-06-09 at 12 09 04 pm](https://user-images.githubusercontent.com/5704285/121336141-85bd2e80-c91b-11eb-9c64-be104d5e6278.jpg)

**Comment by markoprljic** [comment]
As a user I'd be asking myself: What's a shrimp? What's a squid?

**Comment by tamarandom** [comment]
Funny you mention it as that's *exactly* what is being asked on the discord channels! 😂

What a great opportunity we have to clarify! Tie it all together.

**Comment by GriffGreen** [comment]
> @kristoferlund Thanks for the mockup, the header and stats look good. I'm not in favor of visually differentiating members with bigger/smaller fonts. I'd rather see a standard list below and segments just be filter either at the top of the table or on the stats chart. 
> 
> ![Image 2021-06-09 at 12 09 04 pm](https://user-images.githubusercontent.com/5704285/121336141-85bd2e80-c91b-11eb-9c64-be104d5e6278.jpg)
> 

If we say their score like this, we dox their address, there is a requirement to NOT do their address

**Comment by markoprljic** [comment]
Aha, so you say we can have segment filters top 25 etc. but the list should be unsorted? Does the same apply for the token balance?

**Comment by knobsdao** [comment]
We certainly can't link CSTK exact holdings to names, is too easy to find ETH addresses looking a Blockscout with that information. It would also require a plan to update those holdings automagically or frequently as they change.

Thinking of groupings. Grouping by 1-25 / 26-75 / 76-17x works visually but won't reflect certain realities of the long tail.

In CSTK holdings, when someone holds only 1125, it shows they activated but haven't engaged in the community/praise (another case is that minimum + some CSTK for small actions like tweets). Or in MaxTrust, where there's a strong difference between a score lower than 100K and one around 200K. But the number of members with these specs is small, yet grouping them with members with more CSTK/trust isn't ideal.

Anyhow, I don't have a final solution for balancing the groupings. Open to all ideas.

🐳 Higher holdings or trust scores are easier to group. 🦑 and 🦐 came to life talking about the CSTK whales, but the CSTK distribution changed a lot after the burn -now that there are no holders below 1125- and this could be revisited as well. @krisjpi do you remember the exact divisions? I'm having trouble finding it in my notes.

**Comment by GriffGreen** [comment]
@markoprljic yes we don't want to connect people to on chain data... we just show names being grouped

**Comment by kristoferlund** [comment]
@knobsdao Have you come up with any new ideas for the groups?

**Comment by markoprljic** [comment]
I made the mockup in Figma. If we're going to make any changes on filtering or segments please let me know. 

https://www.figma.com/proto/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?page-id=2230%3A6884&node-id=2230%3A7098&viewport=414%2C-278%2C0.5712288618087769&scaling=min-zoom

@knobsdao @kristoferlund @GriffGreen

**Comment by kristoferlund** [comment]
@markoprljic, we decided yesterday to simplify the page somewhat. This is the final version, could you update the design and I'll implement it?

**No pie chart**, because it is confusing and doesn't say much when each segment doesn't have the same numer of members.

**Three segments**, same as before. But, no segment names. 

**Segments are based on max trust**, same as before. Smallish top segment, big middle segment and slightly smaller bottom segment. @knobsdao produces a csv file for each segment, names only.

**Font size separates segments**, similar to my initial dummy.

![image](https://user-images.githubusercontent.com/9698363/122365700-313d3300-cf5b-11eb-90e5-a7150b646085.png)

**Comment by GriffGreen** [comment]
@markoprljic ^^^ Columns vs Music festival style... I don't have an opinion of whats best. 

But the idea is we give every person a Max trust score and 

if its above 600,000 then they are in the top section
If its above 150,000 then they are in the middle section
if its below 150,000 then they are in the last section

and then each section would be sorted in alphabetical order or some other sorting

**Comment by markoprljic** [comment]
@kristoferlund @GriffGreen @knobsdao https://www.figma.com/proto/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?page-id=2230%3A6884&node-id=2230%3A7098&viewport=500%2C-236%2C0.4301266670227051&scaling=min-zoom

**Comment by kristoferlund** [comment]
Great! Consider it done. In a day or two at least.

**Comment by kristoferlund** [comment]
Here is the preview: https://deploy-preview-321--tech-dapp-develop.netlify.app/members

@markoprljic, design ok?

 @knobsdao, only thing needed now is the correct member lists.

**Comment by kristoferlund** [comment]
@markoprljic It doesn't have to be different sized fonts. Please describe how you would like the design to be and I'll fix it. What we do want to avoid is having to give the three groups names, such as: whales / squid / tiny fish or whatever.

**Comment by markoprljic** [comment]
Thanks @kristoferlund 
I was proposing earlier regular list, maybe in 3 columns to fill the space.

**Comment by kristoferlund** [comment]
@markoprljic Ok, but the data we have is one column only (name) and three nameless groups. The plan is not to publish each individual cstk score and trust score.

**Comment by markoprljic** [comment]
I proposed something like this earlier https://www.figma.com/file/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?node-id=2282%3A6890 See if it works.

**Comment by kristoferlund** [comment]
Ok, something like this? https://deploy-preview-321--tech-dapp-develop.netlify.app/members

**Comment by markoprljic** [comment]
I find this much cleaner and better.

**Comment by kristoferlund** [comment]
Great, then we only real need the name lists to complete it, poke poke @knobsdao. (No stress, next week)
