### ISSUE TITLE
Weird 450 DAI pop up is showing up all over the place

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#281]
I don't know why i see this... now i have 450 dai in my wallet....

![Screen Shot 2021-05-27 at 8.20.38 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/4666228f-d8a0-4387-8129-8ce970dcec48)

![Screen Shot 2021-05-27 at 8.25.37 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/e93784ac-ccb4-475a-822d-9979bef2e50d)

![Screen Shot 2021-05-27 at 8.26.01 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/79247c65-fa76-4443-932a-08b5b31b4e8e)

**Comment by kristoferlund** [comment]
Fixed in #303
