### ISSUE TITLE
Pop-up when it should not pop-up 

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#288]
1. I connected without sufficient DAI (I had 0)
2. Griff sent this account 500 DAI
3. Despite numerous shift-refresh, the error about 450 DAI remains
4. See screenshot ;)
5. I am STILL able to pay membership dues though

![Screen Shot 2021-05-28 at 7.22.54 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/c0019c6b-6dfd-4d9c-9281-f23a2d80b9cd)

**Comment by kristoferlund** [comment]
Fixed in #303
