### ISSUE TITLE
Wait screen while tokens are being minted

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#290]
1. After I paid and received the AMAZING confetti I see this screen 
2. Looks like it did not actually go through
3. Can we message, after the graffiti, that the score will take a few minutes before it's updated

![Screen Shot 2021-05-28 at 7.36.30 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/e7a69f9b-b018-49f4-ae47-eb01f8fc3522)

**Comment by GriffGreen** [comment]
Stay on the last screen, until the cstk is minted

**Comment by kristoferlund** [comment]
Addition:

Before the confetti we need to wait for CSTK tokens to be minted. It should also wait for CSLOVE tokens to be minted.

Ideally we would like to signal this in some way to let the user know it is happening.

First:
[spinner] Minting CSTK tokens
[spinner] Minting CSLOVE tokens

Then:
✅ CSTK tokens minted
[spinner] Minting CSLOVE tokens

Finally:
✅ CSTK tokens minted
✅ CSLOVE tokens minted
