### ISSUE TITLE
Logic of when to show the 1-scholarship message

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#292]
The scholarship message should be shown *only* when the value is 900 DAI (the default for when a address has > 900 DAI). 

![Screen Shot 2021-05-28 at 7.41.05 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/d2de0621-4a59-4113-9de5-460d3438ae85)

**Comment by kristoferlund** [comment]
Fixed in #303
