### ISSUE TITLE
I can't see any thing... its like the dashboard node isnt connected or soemthing!?!?

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#293]
![Screen Shot 2021-05-28 at 10.27.48 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/dcd78b59-dfdb-4026-9e70-e88268ee6f90)

For this address: 0x839395e20bbB182fa440d08F850E6c7A8f6F0780

**Comment by GriffGreen** [comment]
![Screen Shot 2021-05-28 at 10.51.53 AM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/838ee60a-9cac-43da-bf50-165be4768537)

**Comment by kristoferlund** [comment]
@aminlatifi I experienced the above as well. But only for a minute or two.

`rpc.xdaichain.com` sometimes takes long to reply.
 
![image](https://user-images.githubusercontent.com/9698363/120045491-687d8b80-c010-11eb-8341-18fad6e910a9.png)
