### ISSUE TITLE
dApp - Bugs from Hatchers. 

### ISSUE THREAD

**Issue by eduardovegap** [commons-stack/swissmem-dapp#305]
Hello Everyone!

I don't know if this is a bug, but a few Hatchers that were on the process to pay their membership dues, encountered the following situation: 

1. 0xE50CefF4eCDe1a76AFc5153A99e5C7F84d1D25c8 got stucked on a loop, and it doesn' allow her to proceed with the payment. ![photo_2021-06-01 17.30.56.jpeg](https://images.zenhubusercontent.com/5fb59e0d956d0a522cd3101d/23df8fda-3c88-442f-82e6-b5417e1bbd39)

I think it's due to the lack of gas.

So my question is, is it possible to just add the notification or a message that remind people that they need to have enough for the gas fee? Since the error like the one form the screenshot happens, but they're unaware why it happens. 

Thanks!

**Comment by GriffGreen** [comment]
# 1

https://etherscan.io/tx/0x69ebf3e55c96a527b07a2c58094a9248726cc0853fb631daa1f39c17797550ab

That's her tx.. she had a low gas price
she needs to speed it up

She doesn't have much ETH, I'll pass her a bit and but she needs to speed up the transaction

**Comment by eduardovegap** [comment]
@GriffGreen thanks, she is in!

**Comment by kristoferlund** [comment]
Status: @aminlatifi takes a look at how complicated it is to detect sped up transactions.

**Comment by aminlatifi** [comment]
> Status: @aminlatifi takes a look at how complicated it is to detect sped up transactions.

I am investigating how to find out user has replaced the tx  by another tx with same data but different gas price.

**Comment by kristoferlund** [comment]
See #289
