### ISSUE TITLE
Hatcher - Change of ETH Address

### ISSUE THREAD

**Issue by eduardovegap** [commons-stack/swissmem-dapp#310]
Hello guys! 

gijsspoor reached out because the eth address listed on our database isn't the eth he uses. 

He is asking the old one (0x657A94a6725145AA0125b71f48264674D3829bc5) to change it to 0x3a868672FEbeEaA91F818F4060EFF2181136dbf4. 

Let me know if it's possible!

Thanks for the help!

**Comment by kristoferlund** [comment]
I think @knobsdao is the one to talk to about this.

**Comment by knobsdao** [comment]
Change made.
