### ISSUE TITLE
The CSLOVE page

### ISSUE THREAD

**Issue by kristoferlund** [commons-stack/swissmem-dapp#313]
Let's add a page to the membership app with the following content:

- Your CSLOVE balance
- Info:
  - What is the CSLOVE and how can you use it? 
  - How do you add it to Metamask?
- Link to store

**Comment by kristoferlund** [comment]
Draft spec: 

![image](https://user-images.githubusercontent.com/9698363/121346581-945d1300-c926-11eb-8a7a-79e1ddefb7e6.png)

**Comment by kristoferlund** [comment]
https://miro.com/app/board/o9J_lAdv6GY=/

**Comment by tamarandom** [comment]
👍👍👍

**Comment by kristoferlund** [comment]
Begun working on this page. @markoprljic do we need a CSLove icon or we just go with the Commons Stack logo?

![image](https://user-images.githubusercontent.com/9698363/121664352-ae722f00-caa7-11eb-81e0-7a4c3daf90a2.png)

**Comment by markoprljic** [comment]
I think someone proposed icon before...

<img width="739" alt="Screenshot 2021-01-25 at 13 55 35" src="https://user-images.githubusercontent.com/5704285/121668526-afa55b00-caab-11eb-9260-18e85e0f69c2.png">

I'll send you SVG.
