### ISSUE TITLE
If the dapp only supports Metamask, we should make that clear here (see screenshot)

### ISSUE THREAD

**Issue by tamarandom** [commons-stack/swissmem-dapp#315]
![Screen Shot 2021-06-15 at 3.43.36 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/07a43c0c-2314-4207-9521-b98215d05e59)

**Comment by kristoferlund** [comment]
Coming update shows only Metamask.

![image](https://user-images.githubusercontent.com/9698363/122195728-e823ab00-ce96-11eb-8d24-d328c0598ca4.png)
