### ISSUE TITLE
Renewal members are confused!! HELP!

### ISSUE THREAD

**Issue by GriffGreen** [commons-stack/swissmem-dapp#338]
<img width="839" alt="Screen Shot 2022-03-25 at 9 20 29 AM" src="https://user-images.githubusercontent.com/14945613/160144705-f217ceda-d3cf-4e56-ba0e-e3571f762c22.png">

Replace the text with:

Membership renewals are open for 2022. By paying 450 DAI or more membership dues you will extend your membership for one more year. You can acquire DAI on [1inch.exchange](https://1inch.exchange/#/r/0x8110d1D04ac316fdCACe8f24fD60C86b810AB15A).

And 

<img width="264" alt="Screen Shot 2022-03-25 at 10 00 17 AM" src="https://user-images.githubusercontent.com/14945613/160146128-a8ed61a0-a603-4a4d-a811-080c845320a2.png">

remove "Additional" from the button

**Comment by GriffGreen** [comment]
@mendesfabio think you can take this?

@kristoferlund can you review and merge?

**Comment by kristoferlund** [comment]
Done deal!

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/9698363/160253794-0f6adcd0-0d4b-44aa-9e56-af2ab66f1e0f.png">
