### ISSUE TITLE
User warning for Max Trust Score

### ISSUE THREAD

**Issue by katzcaban** [commons-stack/swissmem-dapp#85]
User should be warned when they exceed Max trust score

**Comment by GriffGreen** [comment]
There needs to be some code added whenever the  the user connects to the  and then it needs to read the registry to get max trust, and it needs to read the CSTK token  token contract and get the user's token balance, and the total supply and divide by 10,000,000

**Comment by sponnet** [comment]
Let's co-create this in a session

- [ ] read from smart contract  in the API
- [ ] create  the api.js in the front-end
- [ ]  show the pop-up with the content from Figma (https://www.figma.com/file/pSFJQppLaduz91LI8AYIHG/The-Commons-Stack?node-id=1456%3A7411) 
- [ ] cap the CSTK amount to whatever maxtrust is
- [ ] don't cap the DAI amount

**Comment by sponnet** [comment]
minter on xdai  : https://blockscout.com/poa/xdai/address/0x9f92813542Fc66Cd0e530501b4ec62B982B0dEb9/contracts
registry on xdai : https://blockscout.com/poa/xdai/address/0x73e7427428f6C77C180d17F48909780c839954a7/read-contract

**Comment by tamarandom** [comment]
Fixed.

**Comment by GriffGreen** [comment]
This issue was never finished... we need to add a pop up that tells people they have reached their max trust score..

DavidHQ ran into this

![Screen Shot 2021-04-04 at 4.34.56 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/94ff74f2-1589-49a1-b59d-aaeca58b8fd8)

He thought it was a GUI bug

![Screen Shot 2021-04-04 at 4.38.57 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/c3da64bb-2698-4658-a717-2323e7689ca2)

**Comment by GriffGreen** [comment]
There was a figma but i want to change the text:

![Screen Shot 2021-04-04 at 4.37.57 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/1d248ecd-40b4-4717-9d20-cbe1f23fe6b2)

I think it can be shorter.

If you send that much DAI, you will have reached your Max Trust Score. To increase your Max Trust Score, and be able to get a higher CSTK Score, please reach out to the [Commons Stack team on Discord](Link to join Discord)... I had trouble figuring out which link to use for joining discord... will update when i get it.

**Comment by MerlinEgalite** [comment]
No problem!

**Comment by tamarandom** [comment]
😪  Sorry. This is one that could have been tested pretty easily. 

@MerlinEgalite do you think you can take this? Is there any remaining need for @sponnet on this one or should it be assigned to you?

**Comment by MerlinEgalite** [comment]
yeah sure @tamarandom I thought I assigned me to this issue but it turns out no 😅
